nginx:
    build: ./nginx
    links:
        - webserver1:webserver1
    ports:
        - "8080:8080"
webserver1:
    build: ./app
    volumes:
        - ./app:/app
    env_file:
        - ".env"
    ports:
        - "3000"
    links:
        - redis
    command: go build main.go